spring.application.name=pulse

# =========================
# Kafka
# =========================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.pulse.model
spring.kafka.consumer.properties.spring.json.value.default.type=com.pulse.model.LogEvent

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5435/pulse
spring.datasource.username=pulse
spring.datasource.password=pulse

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false